// Scenario 관련 상수 정의

export const mediaData = {
  DIGITAL: {
    'Google Ads': [
      '앱 설치 캠페인_CPA',
      '앱 설치 캠페인_ROAS',
      '범퍼애드_CPM',
      '디맨드젠 캐러셀 광고_CPA',
      '디맨드젠 캐러셀 광고_CPC',
      '디맨드젠 이미지 광고_CPA',
      '디맨드젠 이미지 광고_CPC',
      '디맨드젠 이미지 광고_ROAS',
      '디맨드젠 동영상 광고_CPA',
      '디맨드젠 동영상 광고_CPC',
      '디맨드젠 동영상 광고_ROAS',
      '인피드 동영상 광고_CPV',
      'CPM 마스트헤드_CPM',
      '건너뛸 수 없는 인스트림 광고_CPM',
      '리인게이지먼트 캠페인_CPA',
      '리인게이지먼트 캠페인_ROAS',
      '반응형 디스플레이 광고_CPA',
      '반응형 디스플레이 광고_CPC',
      '반응형 디스플레이 광고_CPM',
      '반응형 디스플레이 광고_ROAS',
      '일반 디스플레이 광고_CPA',
      '일반 디스플레이 광고_CPC',
      '일반 디스플레이 광고_CPM',
      '트루뷰 포 리치_CPM',
      '트루뷰 인스트림_CPV',
      '비디오 액션 캠페인_CPA',
      '비디오 애드 시퀀싱 _CPM',
      '비디오 리치 캠페인 (VRC) 2.0_CPM',
      '비디오 리치 캠페인 (VRC)_CPM',
      '비디오 뷰 캠페인(VVC 2.0)_CPV',
      'YouTube 셀렉트_CPM'
    ],
    'Meta': [
      '경매_앱 홍보_앱 설치수 극대화_facebook&instagram&messenger',
      '경매_앱 홍보_앱 설치수 극대화_instagram',
      '경매_앱 홍보_앱 이벤트 수 극대화_facebook&instagram',
      '경매_인지도_광고 상기도 성과 증대_facebook',
      '경매_인지도_광고 상기도 성과 증대_facebook&instagram',
      '경매_인지도_광고 상기도 성과 증대_instagram',
      '경매_인지도_노출_facebook',
      '경매_인지도_노출_facebook&instagram',
      '경매_인지도_노출_instagram',
      '경매_인지도_동영상 연속 2초 이상 재생 극대화_facebook&instagram',
      '경매_인지도_동영상 연속 2초 이상 재생 극대화_instagram',
      '경매_인지도_일일 고유 도달 극대화_facebook',
      '경매_인지도_일일 고유 도달 극대화_facebook&instagram',
      '경매_인지도_일일 고유 도달 극대화_facebook&instagram&messenger',
      '경매_인지도_일일 고유 도달 극대화_instagram',
      '경매_인지도_ThruPlay 조회 극대화_facebook',
      '경매_인지도_ThruPlay 조회 극대화_facebook&instagram',
      '경매_인지도_ThruPlay 조회 극대화_instagram',
      '경매_참여_전환 이벤트_facebook',
      '경매_참여_동영상 연속 2초 이상 재생 극대화_instagram',
      '경매_참여_링크 클릭수 극대화_instagram',
      '경매_참여_앱 이벤트 수 극대화_facebook',
      '경매_참여_앱 이벤트 수 극대화_facebook&instagram',
      '경매_참여_앱 이벤트 수 극대화_instagram',
      '경매_참여_게시물 참여 극대화_facebook',
      '경매_참여_게시물 참여 극대화_facebook&instagram',
      '경매_참여_게시물 참여 극대화_instagram',
      '경매_참여_알림 설정 극대화_instagram',
      '경매_참여_ThruPlay 조회 극대화_facebook',
      '경매_참여_ThruPlay 조회 극대화_facebook&instagram',
      '경매_참여_ThruPlay 조회 극대화_instagram',
      '경매_잠재 고객_잠재 고객 수 극대화_facebook',
      '경매_잠재 고객_잠재 고객 수 극대화_facebook&instagram',
      '경매_잠재 고객_잠재 고객 수 극대화_instagram',
      '경매_잠재 고객_앱 이벤트 수 극대화_facebook',
      '경매_잠재 고객_앱 이벤트 수 극대화_facebook&instagram',
      '경매_잠재 고객_앱 이벤트 수 극대화_instagram',
      '경매_잠재 고객_전환 잠재 고객 수 극대화_instagram',
      '경매_판매_노출_instagram',
      '경매_판매_링크 클릭수 극대화_instagram',
      '경매_판매_앱 이벤트 수 극대화_facebook',
      '경매_판매_앱 이벤트 수 극대화_facebook&instagram',
      '경매_판매_앱 이벤트 수 극대화_facebook&instagram&messenger',
      '경매_판매_앱 이벤트 수 극대화_instagram',
      '경매_판매_전환값 극대화_facebook&instagram',
      '경매_판매_전환값 극대화_instagram',
      '경매_트래픽_노출_instagram',
      '경매_트래픽_일일 고유 도달 극대화_instagram',
      '경매_트래픽_Instagram 프로필 방문 수 극대화_facebook&instagram',
      '경매_트래픽_Instagram 프로필 방문 수 극대화_instagram',
      '경매_트래픽_랜딩 페이지 조회수 극대화_facebook',
      '경매_트래픽_랜딩 페이지 조회수 극대화_facebook&instagram',
      '경매_트래픽_랜딩 페이지 조회수 극대화_facebook&instagram&messenger',
      '경매_트래픽_랜딩 페이지 조회수 극대화_instagram',
      '경매_트래픽_링크 클릭수 극대화_facebook',
      '경매_트래픽_링크 클릭수 극대화_facebook&instagram',
      '경매_트래픽_링크 클릭수 극대화_facebook&instagram&messenger',
      '경매_트래픽_링크 클릭수 극대화_instagram',
      '예약_인지도_노출_facebook&instagram',
      '예약_인지도_노출_instagram'
    ],
    'NAVER 보장형 DA': [
      'P_브랜드검색_리미티드형_컴박스_검색_일반형_CPT',
      'P_메인_타임보드(비보장)_배너_이미지형(신)_CPM',
      'PM_치지직_인스트림_15초 SKIP(신)_동영상_15초 SKIP형_CPM',
      'M_웹툰_빅배너_통합(신)_배너_동영상_Autoplay(16:9)형_CPM',
      'M_지도_앱_스플래시(1주)_배너_이미지_특수형_CPT',
      'M_웹툰_빅배너_통합(신)_배너_이미지형_CPM',
      'M_브랜드검색_라이트형(신)_검색_이미지_썸네일형_CPT',
      'M_브랜드검색_프리미엄형(신)_검색_프리미엄형_CPT',
      'M_메인_스마트채널_배너_이미지(160)형_CPM',
      'P_브랜드검색_라이트형(신)_검색_이미지형_CPT',
      'M_통합_DA (신)_배너_이미지형_CPM',
      'P_메인_하단(중)_제휴(신)_배너_이미지형_CPT',
      'P_메인_타임보드(신)_배너_동영상_확장형_CPT',
      'M_스노우패밀리_스플래시(CPM)_배너_이미지형(신)_CPM',
      'M_웹툰_논스킵AD_동영상(신)_풀스크린_동영상형_CPM',
      'M_메인_스마트채널_배너_동영상_확장형_CPM',
      'P_브랜드검색_프리미엄형(신)_검색_동영상형_CPT',
      'P_메인_롤링보드(신)_배너_이미지형(신)_CPM',
      'M_신제품검색_검색_이미지형_CPT',
      'M_지도_앱_스마트채널(검색대기)(1주)_배너_이미지형_CPT',
      'P_메인_타임보드(신)_배너_이미지형(신)_CPT',
      'M_메인_브랜딩DA(420)_배너_이미지형_CPM',
      'M_인플루언서_프리미엄DA_배너_이미지형_CPM',
      'P_브랜드검색_프리미엄형(신)_검색_이미지형_CPT',
      'M_브랜드검색_라이트형(신)_검색_이미지_좌측형_CPT',
      'M_브랜드검색_브랜드추천형(프리미엄)_검색_프리미엄형_CPT',
      'M_스노우_스플래시(CPM)_배너_이미지형(신)_CPM',
      'M_브랜드검색_리미티드형_컴박스_검색_일반형_CPT',
      'P_서칭뷰(신)_검색_동영상형_CPT',
      'P_메인_하단(좌)_제휴(신)_배너_이미지형_CPT'
    ],
    'NAVER 성과형 DA': [
      '앱 전환_서비스 통합_CPC',
      '인지도 및 트래픽_밴드_CPC',
      '인지도 및 트래픽_배너 영역_CPC',
      '인지도 및 트래픽_배너 영역(퍼포먼스 네트워크)_CPC',
      '인지도 및 트래픽_커뮤니케이션 영역_CPC',
      '인지도 및 트래픽_피드 영역_CPC',
      '인지도 및 트래픽_네이버 메인_CPC',
      '인지도 및 트래픽_서비스 통합_CPC',
      '인지도 및 트래픽_서비스 통합_CPM',
      '인지도 및 트래픽_스마트 채널_CPC',
      '인지도 및 트래픽_스마트채널 (패밀리 매체)_CPC',
      '인지도 및 트래픽_스마트채널(퍼포먼스 네트워크)_CPC',
      '카탈로그 판매_밴드_CPC',
      '카탈로그 판매_피드 영역_CPC',
      '카탈로그 판매_네이버 메인_CPC',
      '카탈로그 판매_서비스 통합_CPC',
      '카탈로그 판매_쇼핑 영역_CPC',
      '참여 유도_피드 영역_CPC',
      '참여 유도_서비스 통합_CPC',
      '쇼핑 프로모션_네이버 메인_CPC',
      '쇼핑 프로모션_서비스 통합_CPC',
      '쇼핑 프로모션_쇼핑 영역_CPC',
      '동영상 조회_피드 영역_CPV',
      '동영상 조회_인스트림 영역_CPV',
      '동영상 조회_네이버 메인_CPV',
      '동영상 조회_서비스 통합_CPV',
      '웹사이트 전환_밴드_CPC',
      '웹사이트 전환_배너 영역_CPC',
      '웹사이트 전환_커뮤니케이션 영역_CPC',
      '웹사이트 전환_피드 영역_CPC',
      '웹사이트 전환_네이버 메인_CPC',
      '웹사이트 전환_서비스 통합_CPC',
      '웹사이트 전환_스마트 채널_CPC',
      '웹사이트 전환_스마트채널 (패밀리 매체)_CPC'
    ],
    'kakao 모먼트': [
      '디스플레이_전환_픽셀&SDK_CPC',
      '디스플레이_전환_카카오톡채널_CPC',
      '디스플레이_방문_CPC',
      '디스플레이_방문_CPM',
      '포커스 보드_도달_CPT',
      '카카오 비즈보드 CPT_도달_CPT',
      '상품 카탈로그_전환_CPC',
      '카카오톡비즈보드_전환_픽셀&SDK_CPC',
      '카카오톡비즈보드_전환_카카오톡채널_CPA',
      '카카오톡비즈보드_전환_카카오톡채널_CPC',
      '카카오톡비즈보드_방문_CPC',
      '카카오톡비즈보드_방문_CPM',
      '동영상_조회_CPV'
    ],
    'TargetPick': [
      'TargetPick',
      'TargetPick (띠배너)',
      'TargetPick Video',
      'TargetPick Video Plan B',
      'TargetPick (6초)',
      'TargetPick 스플래시',
      'TargetPick (전면동영상)',
      'TargetPick (전면배너)',
      'TargetPick Native (전면배너)'
    ],
    'TikTok': [
      '앱 프로모션_인앱 이벤트_글로벌 앱 번들&Pangle&TikTok_동영상',
      '앱 프로모션_인앱 이벤트_Pangle&TikTok_동영상',
      '앱 프로모션_인앱 이벤트_TikTok_동영상',
      '앱 프로모션_설치_글로벌 앱 번들&Pangle&TikTok_동영상',
      '앱 프로모션_설치_Pangle_동영상',
      '앱 프로모션_설치_TikTok_캐러셀 애즈',
      '앱 프로모션_설치_TikTok_동영상',
      '커뮤니티 상호작용_팔로워_TikTok_동영상',
      '커뮤니티 상호작용_Tiktok 페이지 방문_TikTok_동영상',
      '리드 생성_전환_TikTok_동영상',
      '리드 생성_양식 제출_TikTok_동영상',
      '판매_클릭_Pangle&TikTok_동영상',
      '판매_전환_Pangle&TikTok_카탈로그 애즈',
      '판매_전환_Pangle&TikTok_동영상',
      '판매_전환_Pangle_이미지',
      '판매_전환_Pangle_동영상',
      '판매_전환_TikTok_동영상',
      '판매_인앱 이벤트_Pangle&TikTok_카탈로그 애즈',
      '판매_인앱 이벤트_Pangle&TikTok_동영상',
      '판매_가치_Pangle&TikTok_카탈로그 애즈',
      '판매_가치_Pangle&TikTok_동영상',
      '도달_도달_TikTok_동영상',
      '도달 (예약형)_도달_TikTok_동영상',
      '트래픽_클릭_글로벌 앱 번들&Pangle&TikTok_동영상',
      '트래픽_클릭_글로벌 앱 번들&Pangle_동영상',
      '트래픽_클릭_Pangle&TikTok_동영상',
      '트래픽_클릭_Pangle_이미지',
      '트래픽_클릭_Pangle_동영상',
      '트래픽_클릭_TikTok_캐러셀 애즈',
      '트래픽_클릭_TikTok_동영상',
      '트래픽_랜딩 페이지 조회_글로벌 앱 번들&Pangle&TikTok_동영상',
      '트래픽_랜딩 페이지 조회_글로벌 앱 번들&Pangle_동영상',
      '트래픽_랜딩 페이지 조회_Pangle&TikTok_동영상',
      '트래픽_랜딩 페이지 조회_TikTok_동영상',
      '동영상 조회_6초 조회수_TikTok_동영상',
      '웹사이트 전환_전환_글로벌 앱 번들&Pangle&TikTok_동영상',
      '웹사이트 전환_전환_Pangle&TikTok_동영상',
      '웹사이트 전환_전환_Pangle_동영상',
      '웹사이트 전환_전환_TikTok_동영상',
      '웹사이트 전환_랜딩 페이지 조회_Pangle&TikTok_동영상',
      '웹사이트 전환_가치_글로벌 앱 번들&Pangle&TikTok_동영상',
      '웹사이트 전환_가치_글로벌 앱 번들&Pangle_동영상',
      '웹사이트 전환_가치_Pangle&TikTok_동영상',
      '웹사이트 전환_가치_TikTok_동영상'
    ]
  },
  TV: {
    'CJ ENM': [
      'tvN', 'tvN STORY', 'tvN SHOW', 'OCN', 'Mnet',
      'tvN DRAMA', 'OCN Movie', 'OCN Movie2', 'Tooniverse',
      'tvN Sports', '중화 TV'
    ],
    '지상파': ['KBS2', 'MBC', 'SBS'],
    '종편': ['채널A', 'JTBC', 'MBN', 'TV 조선']
  }
}

export const unlinkedMedia = [
  'SMR', '11번가', 'CJ ONE', 'L.POINT', 'OK캐쉬백', 'SOOP', 'X(구.트위터)',
  '골프존', '네이트', '넷플릭스', '다나와', '당근', '리멤버', '마이클',
  '배달의민족', '블라인드', '스노우', '스카이스캐너', '알바몬', '에브리타임',
  '에이블리', '엔카', '오늘의집', '웨이브', '잡코리아', '직방', '치지직',
  '카카오 T', '카카오뱅크', '카카오페이', '카카오페이지', '쿠팡', '토스',
  '티맵', '티빙', '페이코', '해피포인트'
]

export const sampleBrands = [
  { name: '갤럭시', industry: '전자/IT' },
  { name: 'QLED TV', industry: '전자/IT' },
  { name: '비스포크', industry: '가전' },
  { name: '그램', industry: '전자/IT' },
  { name: '올레드 TV', industry: '전자/IT' },
  { name: '아이오닉', industry: '자동차' },
  { name: '쏘나타', industry: '자동차' },
  { name: '네이버페이', industry: '금융/핀테크' },
  { name: '카카오톡', industry: '소셜/메신저' }
]

export const targetGrpOptions = {
  male: [
    '남성 7~12세', '남성 13~18세', '남성 19~24세', '남성 25~29세',
    '남성 30~34세', '남성 35~39세', '남성 40~44세', '남성 45~49세',
    '남성 50~54세', '남성 55~59세', '남성 60~69세', '남성 70~79세'
  ],
  female: [
    '여성 7~12세', '여성 13~18세', '여성 19~24세', '여성 25~29세',
    '여성 30~34세', '여성 35~39세', '여성 40~44세', '여성 45~49세',
    '여성 50~54세', '여성 55~59세', '여성 60~69세', '여성 70~79세'
  ]
}
